version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: biomedis-app
    ports:
      - "8080:80"
    volumes:
      # Mount storage untuk persistent data
      - ./web-app/storage:/var/www/html/storage
      - ./web-app/database:/var/www/html/database
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    restart: unless-stopped
